travis:
  secure:
    BINSTAR_TOKEN: J1zF03FQMvcPMAg9C+VnJ5Yfo+45S8Ul8WU95DaJZzcIXHhzscL7JckXaSG6yn+Ocptg7AiiJA1I0sKPNp1AUZKt7j/IYBPaxmRpaHR4FvQ66N2DXDsn9yV7bj+by/gjAgiiAQQUjG5COBaJz5A+ePHv0dPVmd+wExvO0Dk/0S5UrCuSm7P2oPTp7XCwUYo78wZeseDL0/N2+o+jq+r7vVeAHklRA4fSYWwup0T68cWMDPuzF5aJ+YHLzUhMihIU5UQktV44WSdgsdRpYqo92S3UhF0P+cUsgH+5bI0rDtAiCWmLqJTPjehiCdPB0zToFakzdRsLxB5cMAhiOp8gOlEcqb+vA91DSQvMzdnSfP9in7u9EvDj+zhu56FtgdzDfuQG6JYqAkZVhLTzw4QntZhioNbmqfVKQeCh4GnykK7tF0jid+XSVdhJ1jltpHKmde/3lf8hoL3eSr9X4vg+HBNyLcNKFg0lK8C5NscD3CDvb2WKd7bG26F/i1Hg7wlpmSEd+7pmH80PWCNBSwegBP0QOdfP9+VgeAEm8uWVXBufoewXexE4QeetlmrXEBrK2DOjddnRCLo3n7MFZ3gw+bI8Fxc254L7Y2eAufqdqS9XCJHOePhvZ3qmEfz/bTG1depg9KOkqvcI6z5T6NQxTgjokVw5lZ3crt6PDjPj9/c=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
