appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: TUDuhZMc9O1D5lmO8e7U5jJFZ6FDvlIYaTEke2Jo+nw2yaTUaGSifVJP0/KA1JjuPRbhhl3OKStxqlra7jP3CPfJUljhhnzGOvXrZU214XZuCYAbM9h93FRCb/0XBp2vj9JPPdG3I57c8NpJaVJ40upsZQwhk95ABnm+i+7yF/yrrNMyhFpuSAM52J1db4sJbEdzWjf/5VJu4yMdCQFbUIVaYqnfjYlpYtkQ3ULPE0d3uBnn8HGksy1YS3BByrh77nihNpZrKXJ7Vsu0ORqpmNsMJpy57ooSDECNaYjU1xZ6OcOCybVFfcIJFIj/f4WaorGv/ao17cBKxalPBjtUB8bzIgZrJ+ihzdnk1wn5cAMjZZb8Bl0dB2CCZfTPseT2uHoJ9rg/HtVElxAaU4LbHRUTg+xM+QKnP9B6NY7aAdKbmArzY5e704rVHlp2zJXz77u01dmsMD1x6+XyVe5N9XJP2nYFL1IkOVyxW0Yn++JuYrNPhMA3VQBU/Vn/aWl4mO//bKUPpGQsffRxhYRhl+1bbROuwTYX2lJrh99Z5eb2Thh7X68qGKeoz1j3Ih4C2B1xcDsMGPns2q5BdySlTTM8OuDBW5rLqsioP3OKt0gBl4HavPYh32PSiLVvNHWjm1mm6p/xB81Q400g7DkRMXuKNh6HuvpfwawP0cq22P0=
conda_forge_output_validation: true
